# alias /usr/local/etc/nginx/conf.d/transformism.conf

upstream transformism_uwsgi {
  server unix:/tmp/uwsgi_transformism.sock;
}

server {
  listen 8000;
  server_name localhost;
  charset utf-8;

  # kill cache
  add_header Last-Modified $date_gmt;
  add_header Cache-Control 'private no-store, no-cache, must-revalidate,  proxy-revalidate, max-age=0';
  if_modified_since off;
  expires off;
  etag off;

  client_max_body_size 75M;

  location / {
    include uwsgi_params;
    uwsgi_pass transformism_uwsgi;
  }

  # static
  location = /favicon.ico {
    alias /Users/K00TSUKA/Sources/transformism/web-server/favicon.ico;
  }
  location = /robots.txt {
    alias /Users/K00TSUKA/Sources/transformism/web-server/robots.txt;
  }
  location = /sitemap.xml {
    alias /Users/K00TSUKA/Sources/transformism/web-server/sitemap.xml;
  }
  location /img/ {
    root /Users/K00TSUKA/Sources/transformism/web-server/views/;
  }
  location /js/ {
    root /Users/K00TSUKA/Sources/transformism/web-server/views/;
  }
  location /css/ {
    root /Users/K00TSUKA/Sources/transformism/web-server/views/;
  }
  location /video/ {
    root /Users/K00TSUKA/Sources/transformism/web-server/views/;
  }
  location /fonts/ {
    root /Users/K00TSUKA/Sources/transformism/web-server/views/;
  }
  location /node_modules/ {
    root /Users/K00TSUKA/Sources/transformism/web-server/views/;
  }
  location /jslibs/ {
    root /Users/K00TSUKA/Sources/transformism/web-server/views/;
  }
  location /documents/ {
    root /Users/K00TSUKA/Sources/transformism/web-server/views/;
  }
}