# alias /usr/local/etc/nginx/conf.d/citywalkservers_local.conf
#
# *please rewrite to your enviroment paths
#

proxy_cache_path /Users/K00TSUKA/Sources/citywalkservers/www/local/nginx/cache levels=1 keys_zone=imagecache:4M inactive=7d max_size=100M;

upstream citywalkservers_uwsgi {
  server unix:/tmp/uwsgi.sock;
}

# cache server
server {
  listen 8001;
  server_name citywalkservers.localhost;
  charset utf-8;

  rewrite_log on;

  client_max_body_size 75M;
  sendfile on;

  location /resources/ {
    proxy_pass http://citywalkservers.localhost:8000;
    proxy_cache imagecache;
    proxy_cache_key $scheme$host$uri$arg_width$arg_height$arg_type$arg_quality$arg_time;
    proxy_cache_valid 200 1d;
    proxy_cache_valid 404 403 1m;
  }

  location / {
    include uwsgi_params;
    proxy_pass http://citywalkservers.localhost:8000;
  }
}

# backend server
server {
  listen 8000;
  server_name citywalkservers.localhost;
  charset utf-8;

  client_max_body_size 75M;
  sendfile on;

  image_filter_buffer 5M;
  resolver 8.8.8.8;

  location / {
      include uwsgi_params;
      uwsgi_pass citywalkservers_uwsgi;
  }

  # static
  location = /favicon.ico {
    alias /Users/K00TSUKA/Sources/citywalkservers/www/favicon.ico;
  }
  location = /robots.txt {
  }
  location /synth_results/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/scripts/TTS/FS2/FastSpeech2/;
  }
  location /img/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/views/;
  }
  location /js/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/views/;
  }
  location /css/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/views/;
  }
  location /video/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/views/;
  }
  location /fonts/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/views/;
  }
  location /node_modules/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/views/;
  }
  location /components/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/views/templates/;
  }
  location /mails/ {
    root /Users/K00TSUKA/Sources/citywalkservers/www/server/application/views/templates/;
  }



  location ~ /resources/(.*\.(jpg|png|jpeg|mp4))$ {

    # default variables
    set $s3host http://data.neuravoice.com;
    set $file $1;
    set $width 150;
    set $height 150;
    set $quality 100;

    if ($file ~ .*.mp4) {
      rewrite ^ /s3_original last;
    }
    if ($query_string !~ .*=.*) {
      rewrite ^ /s3_original last;
    }
    if ($arg_width ~ (\d*)) {
      set $width $1;
    }
    if ($arg_height ~ (\d*)) {
      set $height $1;
    }
    if ($arg_quality ~ (100|[1-9][0-9]|[1-9])){
      set $quality $1;
    }
    if ($arg_type = "resize") {
      rewrite ^ /s3_resize last;
    }

    rewrite ^ /s3_crop last;
  }
  location /s3_original {
    internal;
    proxy_pass $s3host/$file;
  }
  location /s3_resize {
    internal;
    proxy_pass $s3host/$file;
    image_filter resize $width $height;
    image_filter_jpeg_quality $quality;
    error_page 415 = @empty;
  }
  location /s3_crop {
    internal;
    proxy_pass $s3host/$file;
    image_filter crop $width $height;
    image_filter_jpeg_quality $quality;
    error_page 415 = @empty;
  }
  location @empty {
    empty_gif;
  }
}