upstream kazukiotsukacom_uwsgi {
    server unix:/tmp/uwsgi_kazukiotsukacom.sock;
}

server {
    listen 8007;
    server_name kazukiotsukacom.com; # or any domain(s) you have

    charset utf-8;
    client_max_body_size 75M;

    location / {
        include uwsgi_params;
        uwsgi_pass kazukiotsukacom_uwsgi;
    }

    # Example static locations
    location = /favicon.ico {
      alias /src/kazukiotsukacom/web-server/favicon.ico; 
    }
    location = /robots.txt {
      alias /src/kazukiotsukacom/web-server/robots.txt;
    }
    location = /sitemap.xml {
      alias /src/kazukiotsukacom/web-server/sitemap.xml;
    }

    location /img/ {
      root /src/kazukiotsukacom/web-server/views;
    }
    location /js/ {
      root /src/kazukiotsukacom/web-server/views;
    }
    location /css/ {
      root /src/kazukiotsukacom/web-server/views;
    }
    location /video/ {
      root /src/kazukiotsukacom/web-server/views;
    }
    location /fonts/ {
      root /src/kazukiotsukacom/web-server/views;
    }
    location /node_modules/ {
      root /src/kazukiotsukacom/web-server/views;
    }
    location /jslibs/ {
      root /src/kazukiotsukacom/web-server/views;
    }
    location /documents/ {
      root /src/kazukiotsukacom/web-server/views;
    }
}
