[uwsgi]
# socket
socket = /tmp/uwsgi.sock
# pid file
pidfile = /tmp/thinkx.pid
#permissions for the socket file
chmod-socket = 666
# application root
chdir = ../web-server
# virtual env (relative path from application root)
venv = ../web-server/venv
# main.py
module = main
# flask app variable name
callable = app
# master
master = true
# maximum number of worker processes
processes = 10
# clear environment on exit
vacuum = true
# autoreload
py-autoreload = 1
# maximum upload file size
limit-post = 70000000

plugins = python36
