# alias /usr/local/etc/nginx/conf.d/thinkxinc_local.conf

upstream thinkx_uwsgi {
  server unix:/tmp/uwsgi.sock;
}

server {
  listen 8000;
  server_name thinkx.localhost;
  charset utf-8;

  # kill cache
  add_header Last-Modified $date_gmt;
  add_header Cache-Control 'private no-store, no-cache, must-revalidate,  proxy-revalidate, max-age=0';
  if_modified_since off;
  expires off;
  etag off;

  client_max_body_size 75M;

  location / {
    include uwsgi_params;
    uwsgi_pass thinkx_uwsgi;
  }

  # static
  location = /favicon.ico {
    alias /Users/K00TSUKA/Sources/thinkx/web-server/favicon.ico;
  }
  location = /robots.txt {
    alias /Users/K00TSUKA/Sources/thinkx/web-server/robots.txt;
  }
  location = /sitemap.xml {
    alias /Users/K00TSUKA/Sources/thinkx/web-server/sitemap.xml;
  }
  location /img/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /js/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /css/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /video/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /fonts/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /node_modules/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /documents/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
}

server {
  listen 8000;
  server_name nntm.localhost;

  location / {
    # Only rewrite if the path does NOT already begin with /nntm
    rewrite ^/(?!nntm)(.*)$ /nntm/$1 last;

    include uwsgi_params;
    uwsgi_pass thinkx_uwsgi;
  }

    # static
  location = /favicon.ico {
    alias /Users/K00TSUKA/Sources/thinkx/web-server/favicon_NNTM.ico;
  }
  location = /robots.txt {
    alias /Users/K00TSUKA/Sources/thinkx/web-server/robots_NNTM.txt;
  }
  location = /sitemap.xml {
    alias /Users/K00TSUKA/Sources/thinkx/web-server/sitemap_NNTM.xml;
  }
  location /img/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /js/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /css/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /video/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /fonts/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /node_modules/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
  location /documents/ {
    root /Users/K00TSUKA/Sources/thinkx/web-server/views/;
  }
}