server {
    listen 443 ssl;
    server_name jessicas.online www.jessicas.online;  # Handle traffic for both www and non-www URLs

    ssl_certificate /etc/ssl/certs/jessicas.online.crt;
    ssl_certificate_key /etc/ssl/private/jessicas.online.key;

    # Define the backend server
    set $backend "192.168.1.11:8000";  # supercom2

    set $cache_enabled 0;  # 1 for enabled, 0 for disabled

    location ^~ /css/ {
        proxy_pass http://$backend$request_uri;
    }

    location / {
        # Append '/jessicas' to the requests being forwarded to the backend server
        proxy_pass http://$backend/jessicas;

        # Set the headers for real IP and forwarding protocol
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Connection "keep-alive";
    }

    # Static cache
    location /img/ {
        limit_req zone=static_rate_limit burst=3000 nodelay;

        proxy_pass http://$backend/img/;

        # Cache enable mode
        proxy_cache static_cache;
        proxy_cache_valid 200 30d;  # Cache successful responses for 30 days
        proxy_cache_valid 404 10m;  # Cache 404 responses for 10 minutes
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_lock on;
        add_header X-Cache-Status $upstream_cache_status;
        expires 7d;
        add_header Cache-Control "public, max-age=2592000";

        # # Cache disable mode
        # expires -1;  # Disables caching by setting expiration headers in the past
        # add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
        # add_header Pragma "no-cache";  # Ensures older HTTP/1.0 caches also do not store it
    }

    #location /css/main.css {
    #    root /src/loadbalancer;  # Set the base directory for the location
    #    try_files /main.css =404;  # Tries to serve main.css or returns a 404 error if not found
    #}


    # Handle JS files
    location ^~ /js/ {
        proxy_pass http://$backend/js/;
    }
}