function PlayQueue(a,c){this.playList=[];this.overEffectList=[];this.isPlaying=!1;this.stage=c;this.numberOfElements=a;this.currentLineCount=this.currentRowCount=0;this.currentUsedCharNameIndexes=[];this.callback=!1}PlayQueue.prototype.addPlayList=function(a,c,d,h){console.log([a," added to playlist"].join(""));this.playList.push({motion:a,delay:c,numberForNext:d,userInfo:h})};PlayQueue.prototype.popPlayList=function(){this.playList.shift();this.overEffectList.shift()};
PlayQueue.prototype.playListCount=function(){return this.playList.length};PlayQueue.prototype.currentMotionName=function(){return this.playList[0].action};PlayQueue.prototype.currentMotionDelay=function(){return this.playList[0].delay};PlayQueue.prototype.currentMotionsUserInfo=function(){return this.playList[0].userInfo};PlayQueue.prototype.currentMotionsNumberForNext=function(){return this.playList[0].numberForNext};
PlayQueue.prototype.addOverEffect=function(a,c,d){for(var h=0;h<a.length;h++)console.log([a[h]," added to overEffectList"].join(""));this.overEffectList[this.playListCount()-1]={effectTypeList:a,insertNumberList:c,userInfo:d}};PlayQueue.prototype.popCurrentOverEffectList=function(){this.overEffectList[0].effectTypeList.shift();this.overEffectList[0].insertNumberList.shift()};PlayQueue.prototype.currentOverEffectTypeList=function(){var a=this.overEffectList[0];return a?a.effectTypeList:null};
PlayQueue.prototype.currentOverEffectInsertNumberList=function(){var a=this.overEffectList[0];log(this.overEffectList);return a?a.insertNumberList:null};PlayQueue.prototype.currentOverEffectUserInfo=function(){return this.overEffectList[0].userInfo};PlayQueue.prototype.setCurrentRowCount=function(a){this.currentRowCount=a};PlayQueue.prototype.setCurrentLineCount=function(a){this.currentLineCount=a};PlayQueue.prototype.getCurrentRowCount=function(){return this.currentRowCount};
PlayQueue.prototype.getCurrentLineCount=function(){return this.currentLineCount};PlayQueue.prototype.getCurrentUsedCharNameIndexes=function(){return this.currentUsedCharNameIndexes};PlayQueue.prototype.pushCurrentUsedCharNameIndex=function(a){this.currentUsedCharNameIndexes.push(a)};PlayQueue.prototype.resetCurrentUsedCharNameIndexes=function(){this.currentUsedCharNameIndexes=[]};PlayQueue.prototype.setCallback=function(a){this.callback=a};
PlayQueue.prototype.executeCallback=function(){this.callback&&this.callback()};PlayQueue.prototype.reset=function(){console.log("RESET");createjs.Tween.removeAllTweens();this.playList=[];this.overEffectList=[];this.currentLineCount=this.currentRowCount=0;this.currentUsedCharNameIndexes=[];this.callback=!1};
PlayQueue.prototype.play=function(){var a=this.playList[0];log("play");log(this.playList);log(this.currentUsedCharNameIndexes);log(this.callback);if(a)switch(this.isPlaying=!0,console.log(["nextPlayList",a.motion].join(" is ->")),a.motion){case "scatter":this.playScatterMotion();break;case "lineup":this.playLineupMotion();break;case "circle":this.playCircleMotion();break;case "grid":this.playGridMotion();break;case "matrixrandomalpha":this.playMatrixRandomAlphaMotion();break;case "randomalpha":this.playRandomAlphaMotion();
	break;case "textsequence":this.playTextSequenceMotion();break;case "resettextsequence":this.resetTextSequence();break;case "verticaltransfer":this.playVerticalTransferMotion();break;default:console.log("unknown motion")}else console.log("no more play list"),this.breakMotion(),this.executeCallback(),this.callback=!1};PlayQueue.prototype.playNextMotion=function(){console.log("play next");this.popPlayList();this.play()};PlayQueue.prototype.executeOverEffect=function(){switch(this.currentOverEffectTypeList()[0]){case "randomalpha":this.setRandomAlphaEffect()}this.popCurrentOverEffectList()};
PlayQueue.prototype.playGodsDice=function(a,c,d){var h=[];for(i=0;i<a;i++){var l=Math.floor(1E3*Math.random()),m=Math.floor(Math.floor(this.numberOfElements/2)+Math.random()*(this.numberOfElements-1-Math.floor(this.numberOfElements/2))),g=Math.floor(2*Math.random()),f=Math.floor(300+500*Math.random()),b=Math.floor(.1+1*Math.random()),k=Math.floor(Math.random()*(this.numberOfElements-1)),e=Math.floor(6*Math.random());if(c&&-1!=h.indexOf(e)){do e=Math.floor(6*Math.random());while(-1!=h.indexOf(e))}h.push(e);
	switch(e){case 0:this.addPlayList("scatter",l,m,{interval:g,duration:f});break;case 1:this.addPlayList("grid",l,m,{interval:g});break;case 2:this.addPlayList("circle",l,m,{interval:g});break;case 3:this.addPlayList("verticaltransfer",l,m,{position:b,interval:g});break;case 4:this.addPlayList("lineup",l,m,null);break;case 5:this.addPlayList("matrixrandomalpha",l,m,null);break;default:0!=i&&this.addOverEffect(["randomalpha"],[k],null)}}this.setCallback(d);this.play()};
PlayQueue.prototype.playScatterMotion=function(){console.log("Now playing scatter");for(var a=this.currentMotionsUserInfo(),c=a&&a.interval?a.interval:1,a=a&&a.duration?a.duration:1E3,d=null===this.currentMotionDelay()?!1:this.currentMotionDelay(),h=this.numberOfElements,l=this.currentMotionsNumberForNext()?this.currentMotionsNumberForNext():h-1,m=this.currentOverEffectInsertNumberList()?this.currentOverEffectInsertNumberList():[h+1],g=createjs.Tween,f=createjs.Ease,b=0;b<h;b++){var k=this.stage.getChildAt(b),
	e=.4+.6*Math.random(),p=SW*Math.random(),n=SH*Math.random();switch(b){case l:if(!1!==d){var q=this.playNextMotion.bind(this);g.get(k).wait(b*c).to({alpha:0},80,createjs.Ease.circOut).to({alpha:e,x:p,y:n},a,f.circOut).wait(d).call(q)}else console.log("no motion to wait and stop"),g.get(k).wait(b*c).to({alpha:0},80,createjs.Ease.circOut).to({alpha:e,x:p,y:n},a,f.circOut);break;case m[0]:this.executeOverEffect();break;default:g.get(k).wait(b*c).to({alpha:0},80,createjs.Ease.circOut).to({alpha:e,x:p,
		y:n},a,f.circOut)}}};
PlayQueue.prototype.playLineupMotion=function(){console.log("Now playing lineup");for(var a=null===this.currentMotionDelay()?!1:this.currentMotionDelay(),c=this.numberOfElements,d=this.currentMotionsNumberForNext()?this.currentMotionsNumberForNext():c-1,h=this.currentOverEffectInsertNumberList()?this.currentOverEffectInsertNumberList():[c+1],l=createjs.Tween,m=createjs.Ease,g=0;g<c;g++){var f=this.stage.getChildAt(g);switch(g){case d:if(!1!==a){var b=this.playNextMotion.bind(this);l.get(f).wait(1*
		g).to({alpha:0},80,createjs.Ease.circOut).to({alpha:1,x:0+SW*g/c,y:SH/2},1E3,m.circOut).wait(a).call(b)}else console.log("no motion to wait and stop"),l.get(f).wait(1*g).to({alpha:0},80,createjs.Ease.circOut).to({alpha:1,x:0+SW*g/c,y:SH/2},1E3,m.circOut);break;case h[0]:this.executeOverEffect();break;default:l.get(f).wait(1*g).to({alpha:0},80,createjs.Ease.circOut).to({alpha:1,x:0+SW*g/c,y:SH/2},1E3,m.circOut)}}};
PlayQueue.prototype.playCircleMotion=function(){console.log("Now playing circle");for(var a=this.currentMotionsUserInfo(),a=a&&a.interval?a.interval:5,c=null===this.currentMotionDelay()?!1:this.currentMotionDelay(),d=this.numberOfElements-1,h=this.currentMotionsNumberForNext()?this.currentMotionsNumberForNext():d-1,l=this.currentOverEffectInsertNumberList()?this.currentOverEffectInsertNumberList():[d+1],m=createjs.Tween,g=createjs.Ease,f=0;f<d;f++){var b=stage.getChildAt(f),k=SH/2,e=.5*SW,p=SW/2+
	(e-.8*f)*Math.sin(8*f*Math.PI/180),k=k+(e-.8*f)*Math.cos(8*f*Math.PI/180);switch(f){case h:!1!==c?(e=this.playNextMotion.bind(this),log("last element"),m.get(b).wait(f*a).to({alpha:0},80,g.circOut).to({alpha:1,x:p,y:k},1E3,g.circOut).wait(c).call(e)):(console.log("no motion to wait and stop"),m.get(b).wait(f*a).to({alpha:0},80,g.circOut).to({alpha:1,x:p,y:k},1E3,g.circOut));break;case l[0]:this.executeOverEffect();break;default:m.get(b).wait(f*a).to({alpha:0},80,g.circOut).to({alpha:.2+.8*Math.random(),
		x:p,y:k},800,g.circOut)}}};
PlayQueue.prototype.playGridMotion=function(){console.log("Now playing text grid");var a=this.currentMotionsUserInfo(),a=a&&a.interval?a.interval:0,c=null===this.currentMotionDelay()?!1:this.currentMotionDelay(),d=this.numberOfElements,h=this.currentMotionsNumberForNext()?this.currentMotionsNumberForNext():d-1,l=this.currentOverEffectInsertNumberList()?this.currentOverEffectInsertNumberList():[d+1],m=createjs.Tween,g=createjs.Ease,f=this.rowCountWithSidePaddingAndGridWidth(10,30),b=this.lineCountWithRowCount(f),
	k=this.gridHeightWithRowCount(f);this.setCurrentRowCount(f);this.setCurrentLineCount(b);for(b=0;b<d;b++){var e=stage.getChildAt(b);switch(b){case 0:m.get(e).wait(b*a).to({alpha:.2,x:10,y:10,rotation:1},300,g.linear);break;case h:if(!1!==c){var p=this.playNextMotion.bind(this);m.get(e).wait(b*a).to({alpha:.2,x:10+30*b-Math.floor(b/f)*f*30,y:10+Math.floor(b/f)*k,rotation:1},300,g.linear).wait(c).call(p)}else console.log("no motion to wait and stop"),m.get(e).wait(b*a).to({alpha:.2,x:10+30*b-Math.floor(b/
				f)*f*30,y:10+Math.floor(b/f)*k,rotation:1},300,g.linear);break;case l[0]:this.executeOverEffect();break;default:m.get(e).wait(b*a).to({alpha:.2,x:10+30*b-Math.floor(b/f)*f*30,y:10+Math.floor(b/f)*k,rotation:1},300,g.linear)}}};
PlayQueue.prototype.playMatrixRandomAlphaMotion=function(){console.log("Now playing MatrixRandomAlpha");var a=this.getCurrentRowCount();this.getCurrentLineCount();var c=null===this.currentMotionDelay()?!1:this.currentMotionDelay(),d=this.numberOfElements,h=this.currentMotionsNumberForNext()?this.currentMotionsNumberForNext():d-1,l=this.currentOverEffectInsertNumberList()?this.currentOverEffectInsertNumberList():[d+1],m=this.getCurrentUsedCharNameIndexes(),g=createjs.Tween,f=createjs.Ease;if(0==a)this.playNextMotion();
	else for(var b=0;b<d;b++){var k=stage.getChildAt(b),e=b%a,p=Math.floor(b/a),n=String(e*Math.PI/180),n=n.substring(n.length-2,n.length-1),n=parseFloat("0."+n),q=3E3*n,n=40+60*n;switch(b){case h:!1!==c?(e=this.playNextMotion.bind(this),g.get(k).wait(n*p).to({alpha:.1},10,f.linear).wait(c).call(e)):(console.log("no motion to wait and stop"),g.get(k).wait(n*p).to({alpha:.1},10,f.linear));break;case l[0]:this.executeOverEffect();break;default:0==e%2&&-1==m.indexOf(b)?g.get(k).wait(q+n*p).to({alpha:.4+
		.6*Math.random()},10,f.linear):g.get(k).wait(n*p).to({alpha:.1},10,f.linear)}}};
PlayQueue.prototype.playRandomAlphaMotion=function(){console.log("Now playing RandomAlpha");for(var a=null===this.currentMotionDelay()?!1:this.currentMotionDelay(),c=this.numberOfElements,d=this.currentMotionsUserInfo(),h=d&&d.minOpacitiy?d.minOpacity:.3,l=d&&d.maxOpacity?d.maxOpacity:1,d=d&&d.interval?d.interval:10,m=this.currentMotionsNumberForNext()?this.currentMotionsNumberForNext():c-1,c=this.currentOverEffectInsertNumberList()?this.currentOverEffectInsertNumberList():[c+1],g=createjs.Tween,
		f=createjs.Ease,b=0,k=this.numberOfElements;b<k;b++){var e=stage.getChildAt(b);switch(b){case m:if(!1!==a){var p=this.playNextMotion.bind(this);g.get(e).wait(b*d).to({alpha:h+Math.random()*(l-h)},500,f.circOut).wait(500).to({alpha:h+Math.random()*(l-h)},500,f.circOut).wait(a).call(p)}else console.log("no motion to wait and stop"),g.get(e).wait(b*d).to({alpha:h+Math.random()*(l-h)},500,f.circOut).wait(500).to({alpha:h+Math.random()*(l-h)},500,f.circOut);break;case c[0]:this.executeOverEffect();break;
	default:g.get(e).wait(10*b).to({alpha:h+Math.random()*(l-h)},500,f.circOut).wait(500).to({alpha:h+Math.random()*(l-h)},500,f.circOut)}}};
PlayQueue.prototype.playVerticalTransferMotion=function(){console.log("Now playing VerticalTransfer");for(var a=this.currentMotionsUserInfo(),c=a.position?a.position:-.1,d=a&&a.interval?a.interval:10,a=a&&a.delay?a.delay:4E3,h=null===this.currentMotionDelay()?!1:this.currentMotionDelay(),l=this.numberOfElements,m=this.currentMotionsNumberForNext()?this.currentMotionsNumberForNext():l-1,l=this.currentOverEffectInsertNumberList()?this.currentOverEffectInsertNumberList():[l+1],g=createjs.Tween,f=createjs.Ease,
		b=0,k=this.numberOfElements;b<k;b++){var e=stage.getChildAt(b);switch(b){case m:if(!1!==h){var p=this.playNextMotion.bind(this);g.get(e).wait(b*d).to({y:SH*c},a,f.circOut).wait(h).call(p)}else console.log("no motion to wait and stop"),g.get(e).wait(b*d).to({y:SH*c},a,f.circOut);break;case l[0]:this.executeOverEffect();break;default:g.get(e).wait(b*d).to({y:SH*c},a,f.circOut)}}};
PlayQueue.prototype.playTextSequenceMotion=function(){console.log("Now playing text sequence");var a=this.currentMotionsUserInfo(),c=a.text,d=a.interval?a.interval:10;log("interval"+d);var h=null===this.currentMotionDelay()?!1:this.currentMotionDelay(),l=this.numberOfElements;this.currentMotionsNumberForNext()&&this.currentMotionsNumberForNext();for(var l=this.currentOverEffectInsertNumberList()?this.currentOverEffectInsertNumberList():[l+1],m=createjs.Tween,g=createjs.Ease,f=a.sidepd?a.sidepd:150,
		a=a.toppd?a.toppd:70,b=this.rowCountWithSidePaddingAndGridWidth(f,17),k=0,e=0,p=this.numberOfElements;e<p;e++){var n=stage.getChildAt(e);m.get(n).to({alpha:.1},500,g.circOut)}e=0;for(p=c.length;e<p;e++){var n=this.charToCname(c[e]),q=this.cnameToArrIndex(n);-1==q&&(k+=b-(e+k)%b-1);0==(e+k)%b&&"space"==n&&(k-=1);if(n=stage.getChildAt(q))switch(e){case p-1:if(!1!==h){var r=this.playNextMotion.bind(this);m.get(n).wait(e*d).to({alpha:0},80,g.circOut).to({alpha:1,x:f+17*(e+k)-Math.floor((e+k)/b)*b*17,
	y:a+30*Math.floor((e+k)/b),rotation:1},1E3,g.circOut).wait(h).call(r)}else console.log("no motion to wait and stop"),m.get(n).wait(e*d).to({alpha:0},80,g.circOut).to({alpha:1,x:f+17*(e+k)-Math.floor((e+k)/b)*b*17,y:a+30*Math.floor((e+k)/b),rotation:1},1E3,g.circOut);break;case N-1:m.get(n).wait(e*d).to({alpha:0},80,g.circOut).to({alpha:1,x:f+17*(e+k)-Math.floor((e+k)/b)*b*17,y:a+30*Math.floor((e+k)/b),rotation:1},1E3,g.circOut).wait(h).call(r);break;case l[0]:this.executeOverEffect();break;default:m.get(n).wait(e*
	d).to({alpha:0},80,g.circOut).to({alpha:1,x:f+17*(e+k)-Math.floor((e+k)/b)*b*17,y:a+30*Math.floor((e+k)/b),rotation:1},1E3,g.circOut).wait(0)}}};PlayQueue.prototype.resetTextSequence=function(){console.log("Now playing reset text sequence");this.resetCurrentUsedCharNameIndexes();this.playNextMotion()};
PlayQueue.prototype.breakMotion=function(){console.log("Break Motion");this.isPlaying=!0;for(var a=world.GetBodyList(),c=Box2D.Common.Math;a;){var d=a.GetUserData();if(d){var h=new c.b2Vec2(d.x*SCALE,d.y*SCALE),d=new c.b2Mat22.FromAngle(d.rotation*createjs.Matrix2D.DEG_TO_RAD),h=new c.b2Transform(h,d);a.SetTransform(h)}a=a.GetNext()}this.isPlaying=!1};
PlayQueue.prototype.setRandomAlphaEffect=function(){console.log("setrandomAlpha start");for(var a=this.currentOverEffectUserInfo(),c=a&&a.minOpacitiy?a.minOpacity:.3,d=a&&a.maxOpacity?a.maxOpacity:1,a=a&&a.interval?a.interval:10,h=createjs.Tween,l=createjs.Ease,m=0,g=this.numberOfElements;m<g;m++){var f=stage.getChildAt(m);h.get(f).wait(10*a).to({alpha:c+Math.random()*(d-c)},500,l.circOut).wait(500).to({alpha:c+Math.random()*(d-c)},500,l.circOut)}};
PlayQueue.prototype.rowCountWithSidePaddingAndGridWidth=function(a,c){var d=Math.floor((SW-2*a)/c);return 40>d?40:d};PlayQueue.prototype.lineCountWithRowCount=function(a){return Math.ceil(this.numberOfElements/a)};PlayQueue.prototype.gridHeightWithRowCount=function(a){return Math.floor(SH/Math.ceil(this.numberOfElements/a))};
PlayQueue.prototype.cnameToChar=function(a){return-1!=a.indexOf("_")?a.replace(/_/,""):-1!=a.indexOf("dot")?".":-1!=a.indexOf("comma")?",":-1!=a.indexOf("space")?" ":-1!=a.indexOf("quest")?"?":-1!=a.indexOf("quot")?"'":-1!=a.indexOf("dquot")?'"':-1!=a.indexOf("colon")?":":-1!=a.indexOf("at")?"@":-1!=a.indexOf("percent")?"%":-1!=a.indexOf("lbrace")?"{":-1!=a.indexOf("rbrace")?"}":-1!=a.indexOf("lparent")?"(":-1!=a.indexOf("rparent")?")":-1!=a.indexOf("hyphen")?"-":-1!=a.indexOf("and")?"and":-1!=a.indexOf("exclam")?
	"!":-1!=a.indexOf("tild")?"~":-1!=a.indexOf("return")?"\n":a};
PlayQueue.prototype.charToCname=function(a){if(a.match(/[a-z]/))return"_"+a;if(a.match(/[A-Z]/)||a.match(/[0-9]/))return a;if("@"==a)return"at";if("%"==a)return"percent";if("!"==a)return"exclam";if("-"==a)return"hyphen";if("~"==a)return"tild";if("&"==a)return"and";if(" "==a)return"space";if("."==a)return"dot";if(","==a)return"comma";if(":"==a)return"colon";if("?"==a)return"quest";if("{"==a)return"lbrace";if("}"==a)return"rbrace";if(")"==a)return"rparent";if("("==a)return"lparent";if("'"==a)return"quot";
	if('"'==a)return"dquot";if("\n"==a)return"return"};PlayQueue.prototype.cnameToArrIndex=function(a){var c=0,d=this.getCurrentUsedCharNameIndexes();if("return"==a)return-1;for(var h=0,l=cnames.length;h<l;h++)if(cnames[h]==a){c=h;do if(c+=cnames.length,c>this.numberOfElements)break;while(-1!=d.indexOf(c));if(0<c&&c<this.numberOfElements)return d.push(c),c}this.pushCurrentUsedCharNameIndex(c);return c};
function tocenter(a){console.log("tocenter");for(a=0;a<N;a++){var c=stage.getChildAt(a);createjs.Tween.get(c).wait(1*a).to({alpha:0},80,createjs.Ease.circOut).to({alpha:1,x:150+30*a-1200*Math.floor(a/40),y:80+40*Math.floor(a/40)},1E3,createjs.Ease.circOut)}}function todown(a){console.log("todown");console.log("comp fin");for(a=0;a<N;a++){var c=stage.getChildAt(a);createjs.Tween.get(c).wait(1*a).to({alpha:0},80,createjs.Ease.circOut).to({alpha:1,x:0+SW*a/N,y:SH},1E3,createjs.Ease.circOut)}};
