var SW=$(window).width(),SH=$(window).height(),SCALE=1/30,log=function(d){console.log(d)},canvas,context,stage,world,cnames="A B C D E F G H I J K L M N O P Q R S T T T U V W X Y Z _a _a _a _a _b _c _c _d _d _d _e _e _e _e _e _e _e _f _f _g _h _h _i _i _i _i _i _j _k _l _l _l _m _n _n _n _n _n _n _n _o _o _o _o _p _p _p _p _q _r _r _s _s _s _t _t _t _t _t _u _v _w _w _x _y _y _y _z 0 1 2 3 4 5 6 7 8 9 space quest dot quot dquot comma colon colon and at exclam percent tild hyphen hyphen hyphen hyphen lparent rparent rbrace lbrace".split(" "),
  indexfall=0,playQueue,isMenuShown=!1;function tick(d){stage.update()}
  function initCanvas(){function d(a){l=(a.clientX-u.x)/30;m=(a.clientY-u.y)/30}function p(a){return a.GetBody().GetType()!=r.b2_staticBody&&a.GetShape().TestPoint(a.GetBody().GetTransform(),v)?(s=a.GetBody(),!1):!0}var k=$("#canvas");k.attr("width",SW);k.attr("height",SH);canvas=document.getElementById("canvas");context=canvas.getContext("2d");stage=new createjs.Stage(canvas);createjs.Ticker.setFPS(FPS);createjs.MotionGuidePlugin.install(createjs.Tween);createjs.Ticker.addEventListener("tick",function(){if(q&&
			  !n){var a;v=new t(l,m);a=new x;a.lowerBound.Set(l-.001,m-.001);a.upperBound.Set(l+.001,m+.001);s=null;world.QueryAABB(p,a);if(a=s){var e=new y;e.bodyA=world.GetGroundBody();e.bodyB=a;e.target.Set(l,m);e.collideConnected=!0;e.maxForce=300*a.GetMass();n=world.CreateJoint(e);a.SetAwake(!0)}}n&&(q?n.SetTarget(new t(l,m)):(world.DestroyJoint(n),n=null));a=world;a.Step(1/60,10,10);a.DrawDebugData();a.ClearForces();if(!playQueue.isPlaying)for(a=a.GetBodyList();a;){if(e=a.GetUserData())e.x=a.GetPosition().x/
	  SCALE,e.y=a.GetPosition().y/SCALE,e.rotation=a.GetAngle()/createjs.Matrix2D.DEG_TO_RAD;a=a.GetNext()}stage.update()});playQueue=new PlayQueue(N,stage);var t=Box2D.Common.Math.b2Vec2,x=Box2D.Collision.b2AABB,f=Box2D.Dynamics.b2BodyDef,r=Box2D.Dynamics.b2Body,g=Box2D.Dynamics.b2FixtureDef,h=Box2D.Collision.Shapes.b2PolygonShape,k=Box2D.Dynamics.b2DebugDraw,y=Box2D.Dynamics.Joints.b2MouseJointDef;world=new Box2D.Dynamics.b2World(new t(0,gravity),!0);var b=new g;b.density=density_floor;b.friction=friction_floor;
  b.restitution=restitution_floor;f=new f;f.type=r.b2_staticBody;b.shape=new h;b.shape.SetAsBox(SW*SCALE,2*SCALE);f.position.Set(0,(SH-SH*floorInset)*SCALE);world.CreateBody(f).CreateFixture(b);g=new g;g.density=density_object;g.friction=friction_object;g.restitution=restitution_object;f.type=r.b2_dynamicBody;for(b=0;b<N;++b){g.shape=new h;g.shape.SetAsBox(3.75*SCALE,5*SCALE);f.position.x=Math.random()*SW*SCALE;f.position.y=Math.random()*SH*SCALE;var w=b-Math.floor(b/cnames.length)*cnames.length,c=
	  new createjs.Bitmap(["img/char/",cnames[w],".png"].join(""));c.x=0;c.y=0;c.scaleX=.5;c.scaleY=.5;c.regX=7.5;c.regY=10;c.alpha=1*Math.random();c.name=cnames[w]+b;c.index=b;stage.addChild(c);f.userData=c;world.CreateBody(f).CreateFixture(g)}h=new k;h.SetSprite(document.getElementById("canvas").getContext("2d"));h.SetDrawScale(30);h.SetFillAlpha(.5);h.SetLineThickness(1);h.SetFlags(k.e_shapeBit|k.e_jointBit);world.SetDebugDraw(h);var l,m,v,q,s,n,u=function(a){for(var e="",b=0,c=0;"object"==typeof a&&
			  "undefined"!=typeof a.tagName;)c+=a.offsetTop,b+=a.offsetLeft,e=a.tagName.toUpperCase(),"BODY"==e&&(a=0),"object"==typeof a&&"object"==typeof a.offsetParent&&(a=a.offsetParent);return{x:b,y:c}}(document.getElementById("canvas"));document.addEventListener("mousedown",function(a){q=!0;d(a);document.addEventListener("mousemove",d,!0);playQueue.isPlaying&&isMenuShown&&(playQueue.breakMotion(),playQueue.reset());isProductsShown&&hideProducts()},!0);document.addEventListener("mouseup",function(){document.removeEventListener("mousemove",
					  d,!0);q=!1;m=l=void 0},!0);setInterval(function(){if(!playQueue.isPlaying){for(var a=Box2D.Common.Math,b=world.GetBodyList(),c=0,d=indexfall;c<=d;c++)b=b.GetNext();c=new a.b2Vec2(Math.random()*SW*SCALE,0);d=new a.b2Mat22.FromAngle(0*createjs.Matrix2D.DEG_TO_RAD);a=new a.b2Transform(c,d);b.SetTransform(a);indexfall++;indexfall==N&&(indexfall=0)}},fallFrequency);intro()}
			  function intro(){playQueue.setCallback(function(){showMenu()});var d=["ribbon","magnet","shuffle"],p=Math.floor(Math.random()*(d.length+1));log("r="+p);log("catalog "+d[p]);var k=setInterval(function(){switch(d[p]){case "ribbon":playQueue.addPlayList("grid",2E3,100,{interval:3});playQueue.addPlayList("circle",0,600,{interval:3});playQueue.addPlayList("verticaltransfer",1E3,null,{positoin:-.1,interval:6});playQueue.play();break;case "shuffle":playQueue.addPlayList("grid",100,400,{interval:2});playQueue.addPlayList("scatter",
						  2E3,400,{interval:2,duration:500});playQueue.play();break;case "magnet":playQueue.addPlayList("verticaltransfer",0,200,{position:.9,interval:2});playQueue.addOverEffect(["randomalpha"],[350],null);playQueue.addPlayList("verticaltransfer",0,100,{position:.5,interval:1});playQueue.addPlayList("lineup",0,null,null);playQueue.addOverEffect(["randomalpha"],[350],null);playQueue.play();break;default:showMenu()}clearInterval(k)},500)}
			  function messeq(){playQueue.isPlaying||(console.log("now pushed"),playQueue.isPlaying=!0,grid({context:"mes"}))}function servseq(){playQueue.isPlaying||(console.log("now pushed"),playQueue.isPlaying=!0,circle({context:"serv"}))}
			  function clickm1(){console.log("menu1 clicked");playQueue.isPlaying||playQueue.playGodsDice(2,!0,function(){playQueue.reset();playQueue.addPlayList("textsequence",3E3,null,{text:message1,sidepd:150,toppd:70,interval:10});playQueue.addPlayList("resettextsequence",null,null,null);playQueue.addPlayList("textsequence",3E3,null,{text:message2,sidepd:150,toppd:70,interval:10});playQueue.addPlayList("resettextsequence",null,null,null);playQueue.addPlayList("textsequence",3E3,null,{text:message3,sidepd:150,
				  toppd:70,interval:10});playQueue.addPlayList("resettextsequence",null,null,null);playQueue.addPlayList("textsequence",3E3,null,{text:message4,sidepd:150,toppd:70,interval:10});playQueue.addPlayList("resettextsequence",null,null,null);playQueue.addPlayList("textsequence",3E3,null,{text:message5,sidepd:150,toppd:70,interval:10});playQueue.addPlayList("resettextsequence",null,null,null);playQueue.addPlayList("textsequence",3E3,null,{text:message6,sidepd:150,toppd:70,interval:10});playQueue.addPlayList("scatter",
					  2E3,400,{interval:2,duration:500});playQueue.play()})}
			  function clickm2(){console.log("menu2 clicked");isProductsShown||(showProducts(),playQueue.addPlayList("randomalpha",0,300,{minOpacity:.1,maxOpacity:.1,interval:0}),playQueue.addPlayList("grid",1E4,null,{interval:20}),playQueue.addOverEffect(["randomalpha"],[0],{minOpacity:.1,maxOpacity:.1,interval:0}),playQueue.addPlayList("matrixrandomalpha",100,null,null),playQueue.addPlayList("randomalpha",null,null,{minOpacity:.1,maxOpacity:.1,interval:0}),playQueue.play())}
			  function clickm3(){console.log("menu3 clicked");playQueue.isPlaying||(playQueue.reset(),playQueue.playGodsDice(2,!0,function(){playQueue.addPlayList("textsequence",null,null,{text:company,sidepd:150,toppd:70,interval:10});playQueue.play()}))}function clickm4(){console.log("menu4 clicked");playQueue.isPlaying||(playQueue.reset(),playQueue.playGodsDice(100,!1,null))};
